# Generated by Django 3.0.5 on 2023-03-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_no',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
