# Generated by Django 4.1.6 on 2023-04-01 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20230330_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderbase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house1', models.CharField(default='', max_length=50, null=True)),
                ('street1', models.CharField(default='', max_length=50, null=True)),
                ('city1', models.CharField(default='', max_length=50, null=True)),
                ('state1', models.CharField(default='', max_length=50, null=True)),
                ('phone1', models.CharField(blank=True, default='', max_length=50)),
                ('date1', models.DateField(default=datetime.datetime.today)),
                ('status1', models.BooleanField(default=False)),
            ],
        ),
    ]
