# Generated by Django 4.1.6 on 2023-04-01 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_orderbase'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderbase',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.orderbase'),
            preserve_default=False,
        ),
    ]
