# Generated by Django 4.1.6 on 2023-04-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_order_orderbase'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbase',
            name='total',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
