# Generated by Django 4.1.6 on 2023-04-02 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_orderbase_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderbase',
            old_name='city1',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='orderbase',
            old_name='date1',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='orderbase',
            old_name='house1',
            new_name='house',
        ),
        migrations.RenameField(
            model_name='orderbase',
            old_name='phone1',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='orderbase',
            old_name='state1',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='orderbase',
            old_name='status1',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='orderbase',
            old_name='street1',
            new_name='street',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='house',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='street',
        ),
    ]
