# Generated by Django 4.1.6 on 2023-04-02 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_rename_city1_orderbase_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_no',
        ),
    ]
