# Generated by Django 4.1.6 on 2023-04-02 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_order_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbase',
            name='customer',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='store.customer'),
            preserve_default=False,
        ),
    ]
