# Generated by Django 4.1.6 on 2023-04-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='hello',
            field=models.CharField(default="None", max_length=100),
            preserve_default=False,
        ),
    ]
