# Generated by Django 4.1.6 on 2023-04-03 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_customer_hello'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='hello',
        ),
    ]
