# Generated by Django 3.0.5 on 2023-04-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_customer_hello'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
