# Generated by Django 4.1.6 on 2023-04-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_products_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbase',
            name='feedback',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
