# Generated by Django 4.1.6 on 2023-04-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_orderbase_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbase',
            name='reply',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
