# Generated by Django 4.1.6 on 2023-04-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_orderbase_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbase',
            name='feedback',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
