# Generated by Django 4.1.6 on 2023-04-11 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_orderbase_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbase',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='orderbase',
            name='reply',
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbackmsg', models.TextField()),
                ('reply', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.orderbase')),
            ],
        ),
    ]
