# Generated by Django 4.1.6 on 2023-04-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_remove_orderbase_feedback_remove_orderbase_reply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedbackmsg',
            field=models.TextField(null=True),
        ),
    ]
